stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build:
  stage: build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
      command: ["--tls=false", "--host=0.0.0.0:2375"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - main

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - echo "Setting up RBAC permissions..."
    - kubectl apply -f rbac.yaml || echo "RBAC already exists or insufficient permissions"
    - echo "Deploying Healthcare AI Platform..."
    - kubectl create deployment healthcare-ai --image=$IMAGE_NAME --port=8000 --namespace=default --dry-run=client -o yaml > deployment.yaml
    - kubectl apply -f deployment.yaml --namespace=default
    - kubectl expose deployment healthcare-ai --port=80 --target-port=8000 --type=ClusterIP --namespace=default --dry-run=client -o yaml > service.yaml
    - kubectl apply -f service.yaml --namespace=default
    - kubectl create ingress healthcare-ai-ingress --class=nginx --rule="healthcare-ai.owlcloud.fau.edu/*=healthcare-ai:80" --namespace=default --dry-run=client -o yaml > ingress.yaml
    - kubectl apply -f ingress.yaml --namespace=default
    - echo "Healthcare AI Platform deployed at https://healthcare-ai.owlcloud.fau.edu"
  environment:
    name: production
    url: https://healthcare-ai.owlcloud.fau.edu
  only:
    - main
